"""add subtotal to order_items

Revision ID: 02eca079e96e
Revises: 372f0b2ddd58
Create Date: 2026-06-19 00:26:28.857498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02eca079e96e'
down_revision: Union[str, Sequence[str], None] = '372f0b2ddd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('subtotal', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'subtotal')
    # ### end Alembic commands ###
