"""add is_featured to products

Revision ID: 1eed00631d9c
Revises: 3fac9db6d887
Create Date: 2026-08-31 01:01:08.651061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eed00631d9c'
down_revision: Union[str, Sequence[str], None] = '3fac9db6d887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
