"""add_opening_hours_and_advance_days

Revision ID: 27e23db82371
Revises: 2d66f56c05bd
Create Date: 2026-06-09 03:07:36.571230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e23db82371'
down_revision: Union[str, Sequence[str], None] = '2d66f56c05bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_rules', sa.Column('opening_hours_json', sa.JSON(), nullable=True))
    op.add_column('business_rules', sa.Column('max_advance_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_rules', 'max_advance_days')
    op.drop_column('business_rules', 'opening_hours_json')
    # ### end Alembic commands ###
