"""create order_status_history table

Revision ID: 31a2b6240c12
Revises: a246f3abbaaa
Create Date: 2026-07-25 01:37:14.357160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31a2b6240c12'
down_revision: Union[str, Sequence[str], None] = 'a246f3abbaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.drop_index(op.f('ix_order_status-history_id'), table_name='order_status-history')
    op.drop_table('order_status-history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status-history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['admin_users.id'], name=op.f('order_status-history_changed_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_status-history_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_status-history_pkey'))
    )
    op.create_index(op.f('ix_order_status-history_id'), 'order_status-history', ['id'], unique=False)
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
