"""added new columns to model-product, model-order

Revision ID: 8abbac3ad114
Revises: 0d82a1da8a40
Create Date: 2026-08-28 14:01:04.444075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abbac3ad114'
down_revision: Union[str, Sequence[str], None] = '0d82a1da8a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('orders', 'total_price')
    op.drop_column('admin_users', 'full_name')
    # ### end Alembic commands ###
